FROM node:22-alpine AS base
WORKDIR /app
COPY api/package*.json ./
RUN npm ci

FROM base AS dev
COPY api/ .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]

FROM base AS build
COPY api/ .
RUN npm run build

FROM node:22-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
EXPOSE 3000
CMD ["node", "dist/src/main.js"]
