gzip on;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss image/svg+xml;
gzip_min_length 1024;

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        client_max_body_size 50m;
        proxy_pass http://api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # TODO Fase 8: habilitar TLS (certificados Let's Encrypt) aquí.
    # listen 443 ssl;
    # ssl_certificate /etc/letsencrypt/live/appprestamos.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/appprestamos.com/privkey.pem;
    # server_name appprestamos.com;
    # redirect http -> https:
    # listen 80; return 301 https://$host$request_uri;
}
